sudo: false

language: generic

dist: precise

git:
  depth: 10

# don't re-build for tags so that [publish binary] is not re-run
# https://github.com/travis-ci/travis-ci/issues/1532
branches:
 except:
   - /^v[0-9]/

matrix:
  include:
     # Linux
     - os: linux
       compiler: clang
       env: NODE_VERSION="8"
       addons:
         apt:
            sources: [ 'ubuntu-toolchain-r-test' ]
            packages: [ 'libstdc++-4.8-dev']

env:
  global:
    - JOBS: "8"
    - secure: PifMOSnn+mWR1RUptXse+fLvWiTrzg0R/mazO7RWhXHWBKv0uAJ/qV3dI0GIRBLtjG10Iy+tT5RNh1TIbBzB9Y67wMcGvylUPG1+3EOKoBMEPnOD9AgCEQw4SOXfGPx0cq2N6ueSKieCgu1yKN9Wq7XCbE+zTk/DiRNIdLirVoo=
    - secure: cc4esJY1vPXL31IeumAJoKWDDO2BTGFiltwfO1jbTbiV7QT911QUjTUasxXIVpOaHNCpxSTyevPwwTWfzt2EtF92Lli+qhQ2bbzMiDSBZstSrHdAe62Ai2M1oYYUwk/0cABB/2nO9uRyYwITCxpTSNzZBrYhn3C29WqBhPeVDmM=

before_install:
- export PUBLISHABLE=${PUBLISHABLE:-true}
- export COVERAGE=${COVERAGE:-false}
- mkdir ./mason
- curl -sSfL https://github.com/mapbox/mason/archive/v0.15.0.tar.gz | tar --gunzip --extract --strip-components=1 --exclude="*md" --exclude="test*" --directory=./mason
- ./mason/mason install clang++ 4.0.1
- ./mason/mason link clang++ 4.0.1
- export CXX=clang++
- export CC=clang
- export PATH=$(pwd)/mason_packages/.link/bin:$PATH
- scripts/validate_tag.sh
- source ./scripts/install_node.sh ${NODE_VERSION}

install:
# put node-pre-gyp on path
- export PATH=./node_modules/.bin/:$PATH

before_script:
# get commit message
- export COMMIT_MESSAGE=$(git show -s --format=%B $TRAVIS_COMMIT | tr -d '\n')

script:
- if [[ "${NODE_VERSION}" ]]; then ./scripts/build_against_node.sh; fi;
- nm lib/binding/*/node_sqlite3.node | grep "GLIBCXX_" || true
- nm lib/binding/*/node_sqlite3.node | grep "GLIBC_" || true
- if [[ "${NODE_VERSION}" -eq "4" ]]; then ./node_modules/.bin/eslint lib; fi;
# disabled for now: need to port to sudo:false
#- if [[ "${NODE_WEBKIT}" ]]; then ./scripts/build_against_node_webkit.sh; fi;
